name: booking_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_neumorphic: ^3.2.0
  http: ^0.13.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5 
  extended_image: ^7.0.2
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
   - assets/svgs/
    

